### ISSUE TITLE
百度云盘无法下载

### ISSUE THREAD

**Issue by RoryJYL** [adswads/AutoChessMatch#1]
如题所述，无法找到百度云盘中的文件

**Comment by adswads** [comment]
https://pan.baidu.com/s/19jjG6Ty_KJa9RowpgWMQhg
我刚用游客身份上去能看见文件呢，你链接对了么？

**Comment by RoryJYL** [comment]
现在可以了 不知道昨天咋回事儿

**Comment by adswads** [comment]
可以了就行，不行你就自己编译个。没怎么弄过github，我有时间看看怎么加一个发布的程序
